---

- block:
  - name: Uncommenting misc options
    lineinfile:
      path: /etc/pacman.conf
      regexp: "^#{{ item }}"
      line: "{{ item }}"
    loop:
     - Color
     - CheckSpace
     - VerbosePkgLists
     - ParallelDownloads = 5
  
  - name: Adding ILoveCandy option
    lineinfile:
      path: /etc/pacman.conf
      insertafter: 'Color'
      line: 'ILoveCandy'

  - name: Enabling multilib repository
    command: sed -i "/\[multilib\]/,/Include/"'s/^#//' /etc/pacman.conf

  - name: Updating system
    pacman:
      update_cache: yes
      upgrade: yes
  become: true