---

- name: Verifying GRUB install
  shell: |
    test -f /boot/grub/grub.cfg || test -f /boot/efi/grub/grub.cfg
  register: grubcfg
  ignore_errors: true
  failed_when: false

- block:  
  - name: Creating grub backup file
    command: mv /etc/default/grub /etc/default/grub~
  
  - name: Setting up GRUB config file
    copy:
      dest: /etc/default/grub
      content: |
        # GRUB boot loader configuration
        GRUB_DEFAULT=0
        GRUB_TIMEOUT_STYLE=hidden
        GRUB_TIMEOUT=0
        GRUB_DISTRIBUTOR="Arch Linux"
        GRUB_CMDLINE_LINUX_DEFAULT="quiet splash"
        GRUB_CMDLINE_LINUX=""

  - name: Adding nvidia module
    command: sed -i "s/\(GRUB_CMDLINE_LINUX_DEFAULT=\"[^\"]*\)/\1 nvidia_drm.modeset=1/" /etc/default/grub
    when: gpu_vendor.strip() == 'nvidia'

  - name: Updating GRUB
    shell: | 
      grub-mkconfig -o /boot/grub/grub.cfg || grub-mkconfig -o /boot/efi/grub/grub.cfg 

  - name: Installing plymouth
    pacman:
      name: plymouth
      state: present

  when: grubcfg.rc == 0
  become: true