---

- block:
  - name: Installing CPU microcode
    pacman:
      name: "{{ item }}"
      state: present
    loop: "{{ lookup('vars', cpu_vendor.strip() + 'cpu_packages') }}"
    when: cpu_vendor.strip() in ['amd', 'intel']
  
  - name: Installing GPU packages
    pacman:
      name: "{{ item }}"
      state: present
    loop: "{{ lookup('vars', gpu_vendor.strip() + 'gpu_packages') }}"
    when: gpu_vendor.strip() in ['amd', 'intel', 'nvidia']

  - name: Installing linux headers
    pacman:
      name: "{{ item }}"
      state: present
    loop:
      "{{ lookup('pipe', 'cat /usr/lib/modules/*/pkgbase') | split() }}"

  - name: Installing pacman packages
    pacman: 
      name: "{{ item }}"
      state: present
    loop:
      "{{ pacman_packages }}"

  - name: Installing pacman packages
    pacman: 
      name: "{{ item }}"
      state: present
    loop:
      "{{ aur_packages }}"
  become: true