---

- name: Installing CPU microcode
  become: true
  pacman:
    name: "{{ item }}"
    state: present
  loop: "{{ lookup('vars', cpu_vendor.strip() + 'cpu_packages') }}"
  when: cpu_vendor.strip() in ['amd', 'intel']

- name: Installing GPU packages
  become: true
  pacman:
    name: "{{ item }}"
    state: present
  loop: "{{ lookup('vars', gpu_vendor.strip() + 'gpu_packages') }}"
  when: gpu_vendor.strip() in ['amd', 'intel', 'nvidia']
