---

- name: Adding starship to bashrc
  lineinfile:
    path: "/home/{{ ansible_user_id }}/.bashrc"
    line: |
      # Starship
      eval "$(starship init bash)"
    insertbefore: EOF

- name: Downloading GTK theme repository
  git:
    repo: "https://github.com/Fausto-Korpsvart/Tokyo-Night-GTK-Theme.git"
    dest: "{{ download_dir }}/GtkTheme"
    depth: 1

- name: Install GTK theme
  shell: |
    ./install.sh -t grey -c dark --libadwaita --tweaks black
  args:
    chdir: "{{ download_dir }}/GtkTheme/themes"

- name: Downloading dotfiles
  get_url: 
    url: https://github.com/x86-mota/dotfiles/archive/refs/heads/main.zip
    dest: "{{ download_dir }}/dotfiles.zip"
    force: true

- name: Extracting files
  unarchive:
    src: "{{ download_dir }}/dotfiles.zip"
    dest: "{{ download_dir }}"

- name: Copying dotfiles to the .config folder
  copy:
    src: "{{ download_dir }}/dotfiles-main/"
    dest: "/home/{{ ansible_user_id }}/.config"
    force: true

- name: Setting up gsettings
  shell: |
    gsettings set org.gnome.desktop.interface color-scheme prefer-dark
    gsettings set org.gnome.desktop.interface gtk-theme TokyoNight-Grey-Dark
    gsettings set org.gnome.desktop.interface icon-theme Papirus-Dark
    gsettings set org.gnome.desktop.interface cursor-theme Bibata-Modern-Ice
    gsettings set org.gnome.desktop.interface cursor-size 24
    gsettings set org.gnome.desktop.interface font-name "JetBrainsMono Nerd Font 11"
    gsettings set org.gnome.desktop.interface document-font-name "JetBrainsMono Nerd Font 11"
    gsettings set org.gnome.desktop.interface monospace-font-name "JetBrainsMono Nerd Font 11"
    xdg-settings set default-web-browser brave-browser.desktop
    for ext in png jpeg jpg gif svg+xml; do
      xdg-mime default org.gnome.eog.desktop image/$ext;
    done
    xdg-mime default org.gnome.Evince.desktop application/pdf
    xdg-mime default sublime_text.desktop text/plain

- name: Installing VS Code extensions
  command: code --install-extension "{{ item }}"
  loop:
    - enkia.tokyo-night
    - miguelsolorio.symbols
    - ms-python.python
    - postman.postman-for-vscode
    - ms-azuretools.vscode-docker
    - hashicorp.terraform
    - redhat.vscode-yaml
