---

- name: Adding starship to bashrc
  lineinfile:
    path: "/home/{{ ansible_user_id }}/.bashrc"
    line: |
      # Starship
      eval "$(starship init bash)"
    insertbefore: EOF

- name: Downloading GTK theme repository
  git:
    repo: "https://github.com/Fausto-Korpsvart/Tokyo-Night-GTK-Theme.git"
    dest: "{{ download_dir }}/GtkTheme"
    depth: 1

- name: Install GTK theme
  shell: |
    ./install.sh --theme grey --color dark --libadwaita --tweaks black
  args:
    chdir: "{{ download_dir }}/GtkTheme/themes"

- name: Downloading dotfiles
  get_url: 
    url: https://github.com/x86-mota/dotfiles/archive/refs/heads/main.zip
    dest: "{{ download_dir }}/dotfiles.zip"
    force: true

- name: Extracting files
  unarchive:
    src: "{{ download_dir }}/dotfiles.zip"
    dest: "{{ download_dir }}"

- name: Copying dotfiles to the .config folder
  copy:
    src: "{{ download_dir }}/dotfiles-main/"
    dest: "/home/{{ ansible_user_id }}/.config"
    force: true