---

- name: Adding user in groups 
  become: true
  command: sudo usermod -aG "{{ item }}" "{{ ansible_user_id }}"
  loop:
    - docker
    - input

- name: Adding starship to bashrc
  lineinfile:
    path: "/home/{{ ansible_user_id }}/.bashrc"
    line: |
      
      # Starship
      eval "$(starship init bash)"
    insertbefore: EOF

- name: Downloading GTK theme repository
  git:
    repo: "https://github.com/Fausto-Korpsvart/Tokyo-Night-GTK-Theme.git"
    dest: "{{ download_dir }}/GtkTheme"
    depth: 1

- name: Downloading Dracula theme
  get_url: 
    url: https://github.com/dracula/gtk/archive/master.zip
    dest: "{{ download_dir }}/Dracula.zip"
    force: true

- name: Extracting files
  unarchive:
    src: "{{ download_dir }}/Dracula.zip"
    dest: "{{ download_dir }}"

- name: Configuring theme
  shell: |
    mkdir -p /home/{{ ansible_user_id }}/.themes
    mkdir -p /home/{{ ansible_user_id }}/.config/gtk-4.0
    mv "{{ download_dir }}"/gtk-master /home/{{ ansible_user_id }}/.themes/Dracula
    ln -sf /home/{{ ansible_user_id }}/.themes/Dracula/assets/ /home/{{ ansible_user_id }}/.config
    ln -sf /home/{{ ansible_user_id }}/.themes/Dracula/assets/ /home/{{ ansible_user_id }}/.config/gtk-4.0/
    ln -sf /home/{{ ansible_user_id }}/.themes/Dracula/gtk-4.0/gtk.css /home/{{ ansible_user_id }}/.config/gtk-4.0/
    ln -sf /home/{{ ansible_user_id }}/.themes/Dracula/gtk-4.0/gtk-dark.css /home/{{ ansible_user_id }}/.config/gtk-4.0/

- name: Downloading dotfiles
  get_url: 
    url: https://github.com/x86-mota/dotfiles/archive/refs/heads/main.zip
    dest: "{{ download_dir }}/dotfiles.zip"
    force: true

- name: Extracting files
  unarchive:
    src: "{{ download_dir }}/dotfiles.zip"
    dest: "{{ download_dir }}"

- name: Copying dotfiles to the .config folder
  copy:
    src: "{{ download_dir }}/dotfiles-main/config/"
    dest: "/home/{{ ansible_user_id }}/.config"
    force: true

- name: Copying scripts to .local/share/bin
  copy:
    src: "{{ download_dir }}/dotfiles-main/scripts/"
    dest: "/home/{{ ansible_user_id }}/.local/share/bin"
    mode: '744'
    force: true
  with_fileglob:
    - "{{ download_dir }}/dotfiles-main/scripts/*.sh"

- name: Setting up gsettings
  shell: |
    gsettings set org.gnome.desktop.interface color-scheme prefer-dark
    gsettings set org.gnome.desktop.interface gtk-theme "Dracula"
    gsettings set org.gnome.desktop.wm.preferences theme "Dracula"
    gsettings set org.gnome.desktop.interface icon-theme Papirus-Dark
    gsettings set org.gnome.desktop.interface cursor-theme Vimix-cursors
    gsettings set org.gnome.desktop.interface cursor-size 24
    gsettings set org.gnome.desktop.interface font-name "JetBrainsMono Nerd Font 11"
    gsettings set org.gnome.desktop.interface document-font-name "JetBrainsMono Nerd Font 11"
    gsettings set org.gnome.desktop.interface monospace-font-name "JetBrainsMono Nerd Font 11"
    xdg-settings set default-web-browser brave-browser.desktop
    for ext in png jpeg jpg gif svg+xml; do
      xdg-mime default org.xfce.ristretto.desktop image/$ext;
    done
    xdg-mime default org.gnome.Evince.desktop application/pdf
    xdg-mime default code.desktop text/plain

- name: Installing VS Code extensions
  command: code --install-extension "{{ item }}"
  loop:
    - dracula-theme.theme-dracula
    - miguelsolorio.symbols
    - ms-python.python
    - ms-azuretools.vscode-docker
    - hashicorp.terraform
    - redhat.vscode-yaml
