---

- name: Get some system information
  import_tasks: 01-syscheck.yml

- name: Edit pacman.conf
  import_tasks: 02-pacman.yml

- name: Set up bootloader
  import_tasks: 03-bootloader.yml

- name: Install AUR Helper
  import_tasks: 04-aurhelper.yml

- name: Install packages
  import_tasks: 05-install-packages.yml

- name: Set up system
  import_tasks: 06-setup-system.yml

- name: Install QEMU/KVM
  import_tasks: 07-qemu.yml

- name: Set up user
  import_tasks: 08-user-settings.yml