---

pacman_config_path: /etc/pacman.conf
grub_config_path: /etc/default/grub
grub_cfg_path: /boot/grub/grub.cfg
download_dir: "/home/{{ ansible_user_id }}/ansible"
aur_helper: yay

amdcpu_packages:
  - amd-ucode

intelcpu_packages:
  - intel-ucode

amdgpu_packages:
  - libva-mesa-driver
  - mesa
  - mesa-vdpau
  - vulkan-icd-loader
  - vulkan-radeon
  - lib32-libva-mesa-driver
  - lib32-mesa
  - lib32-mesa-vdpau
  - lib32-vulkan-icd-loader
  - lib32-vulkan-radeon
  - xf86-video-amdgpu

intelgpu_packages:
  - mesa
  - vulkan-intel
  - lib32-mesa
  - lib32-vulkan-intel
  - xf86-video-intel

nvidiagpu_packages:
  - libva
  - libva-nvidia-driver
  - mesa
  - nvidia-dkms
  - nvidia-settings
  - nvidia-utils
  - vulkan-headers
  - vulkan-icd-loader
  - vulkan-tools
  - lib32-nvidia-utils
  - lib32-vulkan-icd-loader